//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrents_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime Start_date { get; set; }
        public Nullable<decimal> Tot_price { get; set; }
        public string Car_name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Date_number { get; set; }
        public int CustomerId { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
